version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    command: gunicorn quiz.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./env/.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:5-alpine
  celery_worker:
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    image: quiz_celery_celery_worker
    command: celery -A quiz worker -l INFO
    volumes:
      - /usr/src/app/
    env_file:
      - ./env/.env.dev
    depends_on:
      - redis
      - db
      - web

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    image: quiz_celery_celery_beat
    command: celery -A quiz beat -l INFO
    volumes:
      - /usr/src/app/
    env_file:
      - ./env/.env.dev
    depends_on:
      - redis
      - db
      - web
  flower:
    image: mher/flower
    volumes:
      - /usr/src/app/
    env_file:
      - ./env/.env.dev
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
      - web
      - celery_beat
      - celery_worker

volumes:
  postgres_data:
  static_volume:
  media_volume:
