# Generated by Django 3.2.6 on 2021-08-28 18:34

import apps.quiz_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='address_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='address_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='address_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='address_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='address_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='code',
            field=models.CharField(default=apps.quiz_user.models.user_code_generator, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='designations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizuser',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
